spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/slife_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:An123}

logging.level.com.slife.marketplace=DEBUG

spring.devtools.restart.enabled=true
