spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/slife_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

logging.level.com.slife.marketplace=DEBUG

# DevTools: t? ??ng restart khi build l?i (mvn compile ho?c IDE build)
spring.devtools.restart.enabled=true
