spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/slife_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:An123}

# Google SSO (chỉ cho phép @fpt.edu.vn)
google.clientId=${GOOGLE_CLIENT_ID:318344558779-vee2ail43gcadoi97fo2q9122jm9qe7k.apps.googleusercontent.com}
google.clientSecret=${GOOGLE_CLIENT_SECRET:}

logging.level.com.slife.marketplace=DEBUG
